apiVersion: v1
kind: Service
metadata:
  name: net-watch-prober-svc
  namespace: default
  labels:
    app: net-watch-prober
spec:
  selector:
    app: net-watch-prober
  ports:
    - name: metrics
      protocol: TCP
      port: 8000        # El puerto que expone el Service
      targetPort: 8000  # El puerto interno de tu contenedor Python